eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
management:
    tracing:
        sampling:
            probability: 1.0
server:
    port: 8081
spring:
    application:
        name: job-service
    config:
        import: configserver:http://localhost:8080
    datasource:
        password: root
        url: jdbc:postgresql://localhost:5432/microservices
        username: postgres
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
